services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\UniversignService:
        arguments:
            $apiUrl: '%env(UNIVERSIGN_API_URL)%'
            $apiKey: '%env(UNIVERSIGN_API_KEY)%'
            $webhookSecret: '%env(UNIVERSIGN_WEBHOOK_SECRET)%'

    App\Service\LetrecoService:
        arguments:
            $apiUrl: '%env(LETRECO_API_URL)%'
            $apiKey: '%env(LETRECO_API_KEY)%'
            $webhookSecret: '%env(LETRECO_WEBHOOK_SECRET)%'
